### PR TITLE
CALL + RET

### PR DESCRIPTION
**Pull request by NicoM1**
This still isnt working, something is really weird with the STOP command in my test, its supposed to be going

1)JUMP TO 4
2)DECREMENT
3)STOP
4)INCREMENT
5)INCREMENT
6)RETURN TO 2

but for some reason it doesn't seem to be stopping correctly at the end (although it is hitting the stop?)

if anyone has any ideas let me know

### CODE REVIEW

**Comment by NicoM1** [comment]
Actually I might be using DEC wrong and the call + ret is fine

**Comment by Eiyeron** [comment]
Checking the opcodes shows me that STOP needs a NOP just after it. The code sample should be;
```
...
DECREMENT
STOP
NOP
INCREMENT
...

I haven't set the corrupted opcode behavior (STOP+anything else than NOP) but that's something to take account of.

Edit : Fixed it

**Comment by Eiyeron** [comment]
What's next is making the unit test a bit more verbose, like checking SP or PC.

**Comment by NicoM1** [comment]
I'm merging this, it passes all tests nicely and covers a fair bit of ground.

**Pull request merged**
